CONFIG:
  ConfigPath: /usr/local/oms/omeye/omeye2/monitoring/conf.d/monitoring-prod.ini
REDIS:
  RedisContainerName: oms-redis
  RedisHost: localhost
  RedisPort: 6379
  Username: root
  Password: oms20190211!