CONFIG:
  ConfigPath: /mnt/c/Users/sshsy/oms/monitoring/conf.d/monitoring-local.ini
REDIS:
  RedisContainerName: redis
  RedisHost: localhost
  RedisPort: 6379
  Username: root
  Password: oms20190211!