SETTING:
  rootPath: /mnt/c/Users/sshsy/oms
  serverIP: localhost
  serverPort: 4755
  userPassword: oms20190211!
  networkName: enp4s0
  imageProcessingServiceName: omeye2.sc_v2.service
  mediaStreamingServiceName: omeye2.mediaserver.service
  backendServiceName: omeye2.back.service
  middleServerServiceName: win11
  aiServiceName: omeye2.sc_model.service
  middleServiceName: middleserver
  token: onemoresecurity20190211!
VERSION:
  backend: 1.0.0.0
  frontend: 1.0.0.0
  ai: 2.0.0.6
  imageProcessing: 1.0.0.0
  mediaStreaming: 1.0.0.0
CATEGORY:
  ai: ai
  frontend: frontend
  backend: backend
  past_backend: backend
  imageProcessing: image-processing
  mediaStreaming: media-streaming
  monitoring: monitoring
REDIS:
  RedisContainerName: redis
  RedisHost: localhost
  RedisPort: 6379
  Username: root
  Password: oms20190211!
