version: "3.8"
services:
  auth:
    container_name: "auth"
    env_file:
      - '.env'
    image: kmg2331/oms-authentication-api
    user: root
    volumes:
      - ./auth/jars:/workspace/jars
      - ./log/auth:/workspace/log
    ports:
      - "8099:8099"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - default
  gateway:
    container_name: "gateway"
    user: root
    env_file:
      - '.env'
    image: kmg2331/oms-api-gateway
    volumes:
      - ./gateway/jars:/workspace/jars
      - ./gateway/config:/workspace/config
      - ./log/gateway:/workspace/log
    ports:
      - "8070:8070"
    environment:
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - default
  user:
    container_name: "user"
    image: kmg2331/oms-user-api
    user: root
    env_file:
      - '.env'
    volumes:
      - ./user/jars:/workspace/jars
      - ./log/user:/workspace/log
    ports:
      - "8098:8098"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - default
  vms:
    container_name: "vms"
    image: kmg2331/oms-vms-api
    user: root
    env_file:
      - '.env'
    volumes:
      - ./vms/jars:/workspace/jars
      - ./log/vms:/workspace/log
      - ./vms/config:/workspace/config
      - ./files/tmp:/files/tmp
    ports:
      - "8072:8072"
      - "554:554"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - default
  settings:
    container_name: "settings"
    image: kmg2331/oms-setting-api
    user: root
    env_file:
      - '.env'
    volumes:
      - ./log/settings:/workspace/log
    ports:
      - "8071:8071"
    environment:
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - default
  selective-main:
    container_name: "selective-main"
    image: kmg2331/selective-main-api
    user: root
    env_file:
      - '.env'
    volumes:
      - ./main:/main
      - ./log/main:/workspace/log
      - ./main/jars:/workspace/jars
      - ./files/tmp:/files/tmp
    ports:
      - "18085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - default
  selective-ai:
    container_name: "selective-ai"
    image: kmg2331/selective-ai-api
    user: root
    env_file:
      - '.env'
    volumes:
      - ./log/selective-ai:/workspace/log
      - ./selective-ai/jars:/workspace/jars
    ports:
      - "18086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - default
networks:
  default:
    driver: bridge
    attachable: true
